name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Project (Dev)
        run: npm run build:dev

      - name: Lint TypeScript
        run: npm run lint:ts

      - name: Lint SCSS
        run: npm run lint:scss

      - name: Run Unit Tests
        run: npm run unit

